<a href="https://colab.research.google.com/github/vijaykondapalli/Pytorch-Training/blob/main/Distribution_and_sampling_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch.distributions as dist


In [2]:
bernouli = dist.Bernoulli(0.5)
sample_10 = bernouli.sample((10,))
print(sample_10)

tensor([1., 1., 0., 1., 1., 1., 0., 0., 1., 0.])


In [4]:
bernouli = dist.Bernoulli(0.5)
sample_100 = bernouli.sample((100,))
print(sample_10)

tensor([0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1.,
        0., 1., 0., 0., 1., 1., 1., 0., 0., 1.])


In [6]:
sample_1000 = bernouli.sample((1000,))
print(sample_1000)

tensor([1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
        0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
        1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
        1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
        1., 1., 0., 1., 0., 0., 1., 1., 

In [8]:
sample_100000 = bernouli.sample((100000,))
print(sample_100000)

tensor([0., 0., 0.,  ..., 1., 1., 1.])


torch.Size([100000])


In [13]:
# mean and varian of all of my samples
mean_10 = sample_10.mean()
variance_10 = sample_10.var()

print(f"Sample 10 - Mean: {mean_10}, Variance: {variance_10}")

mean_100 = sample_100.mean()
variance_100 = sample_100.var()

print(f"Sample 100 - Mean: {mean_100}, Variance: {variance_100}")

mean_1000 = sample_1000.mean()
variance_1000 = sample_1000.var()

print(f"Sample 1000 - Mean: {mean_1000}, Variance: {variance_1000}")

mean_100000 = sample_100000.mean()
variance_100000 = sample_100000.var()

print(f"Sample 100000 - Mean: {mean_100000}, Variance: {variance_100000}")


Sample 10 - Mean: 0.5199999809265137, Variance: 0.2521212100982666
Sample 100 - Mean: 0.4000000059604645, Variance: 0.24242424964904785
Sample 1000 - Mean: 0.5049999952316284, Variance: 0.2502252161502838
Sample 100000 - Mean: 0.4999699890613556, Variance: 0.25000250339508057
