<a href="https://colab.research.google.com/github/vijaykondapalli/Pytorch-Training/blob/main/Distribution_and_sampling_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.distributions as dist

In [11]:
## lets create a bernouli distribution
bernoulli_dist = dist.Bernoulli(torch.tensor([0.5]))
## Print sample
for i in range(10):
  print(bernoulli_dist.sample())


tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])


In [25]:
## draw 1000 samples
##samples = bernoulli_dist.sample((1000,))
bernoulli_samples = [bernoulli_dist.sample() for i in range(1000)]
## Print sample
print(f"mean: {torch.mean(torch.stack(bernoulli_samples))}")
print(f"variance: {torch.var(torch.stack(bernoulli_samples))}")


mean: 0.48899999260902405
variance: 0.2501291334629059


In [26]:
## Lets create normal distribution
normal_dist = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
## Print sample
for i in range(10):
  print(normal_dist.sample())

tensor([0.5098])
tensor([-1.3657])
tensor([0.8620])
tensor([0.6375])
tensor([0.0482])
tensor([1.3309])
tensor([-0.4792])
tensor([1.4291])
tensor([0.6747])
tensor([-0.0349])


In [35]:
normal_samples = [normal_dist.sample() for i in range(1000)]
print(f"mean: {torch.mean(torch.stack(normal_samples))}")
print(f"variance: {torch.var(torch.stack(normal_samples))}")



mean: -0.01595495082437992
variance: 1.0407270193099976
