<a href="https://colab.research.google.com/github/vijaykondapalli/Pytorch-Training/blob/main/Distribution_and_sampling_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.distributions as dist

In [11]:
## lets create a bernouli distribution
bernoulli_dist = dist.Bernoulli(torch.tensor([0.5]))
## Print sample
for i in range(10):
  print(bernoulli_dist.sample())


tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])


In [25]:
## draw 1000 samples
##samples = bernoulli_dist.sample((1000,))
samples = [bernoulli_dist.sample() for i in range(1000)]
## Print sample
print(f"mean: {torch.mean(torch.stack(samples))}")
print(f"variance: {torch.var(torch.stack(samples))}")


mean: 0.48899999260902405
variance: 0.2501291334629059
