<a href="https://colab.research.google.com/github/vijaykondapalli/Pytorch-Training/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2 + 5


7

In [24]:
import torch

In [25]:
import numpy as np

# **LISTS**

In [26]:
my_list = [[1,2,3,4,5] ,[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

### **Numpy Arrays**

In [27]:
np1 = np.random.rand(3,4)
np1

array([[0.16782844, 0.87901737, 0.31672534, 0.0479741 ],
       [0.73890177, 0.67711343, 0.31810114, 0.3450023 ],
       [0.93013947, 0.17690724, 0.77656228, 0.16319095]])

In [28]:
np1.dtype

dtype('float64')

# **Tensors**

In [32]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[-0.5474, -1.9520, -0.2690, -0.4759],
        [ 1.0916,  1.1577, -1.4260, -0.9299],
        [ 0.2027, -0.0176, -0.8655,  0.0079]])

In [34]:
tensor_3d = torch.randn(2,3,4)
tensor_3d


tensor([[[-0.1050,  1.5644,  1.3423, -0.1539],
         [ 0.4163,  0.9820, -1.1480,  0.5498],
         [ 0.2896, -0.3834, -0.2992,  2.1512]],

        [[-2.4981, -1.0289, -2.2572, -0.1820],
         [ 0.4327, -0.7905,  0.0113,  0.2305],
         [ 1.0837,  1.7450,  0.7757,  0.9484]]])

In [35]:
tensor_3d.dtype

torch.float32